name: siakad_app
description: SIAKAD - Sistem Informasi Akademik SMA Negeri 1 Cikalong
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Design System
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0

  # Routing
  go_router: ^15.1.2

  # State Management
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.7.0
  supabase_flutter: ^2.8.4

  # Local Storage
  shared_preferences: ^2.3.4

  # Image Handling
  cached_network_image: ^3.4.1

  # Charts
  fl_chart: ^0.70.2

  # QR Scanner (Siswa module)
  mobile_scanner: ^6.0.5

  # PDF & Printing (Wali Kelas e-Rapor)
  pdf: ^3.11.1
  printing: ^5.13.4

  # Date & Number Formatting
  intl: ^0.20.2

  # Cupertino Icons
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  flutter_quill: ^11.5.0
  flutter_quill_delta_from_html: ^1.5.3
  flutter_localizations:
    sdk: flutter
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoSekolah.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
